<?php
	if ($data['account_name'])
	{
		$ant_cust_svr = ($data['ant_cust_svr']) ? $data['ant_cust_svr'] : "aereus.ant.aereus.com";

		$HIDE_MESSAGES = true; // hide messages

		// Create account
		$ACCOUNT_NAME = strtolower($data['account_name']);
		$ACCOUNT_DB = "ant_$ACCOUNT_NAME";

		// Create database
		$dbhSys->fDateStyleSet = true; // prevent query from setting date style. Create does not like multiple commands.
		$ret = $dbhSys->Query("create database $ACCOUNT_DB with encoding='UTF8' template=".$data['template_database'].";");

		$result = $dbhSys->Query("insert into accounts (name, database) values('$ACCOUNT_NAME', '$ACCOUNT_DB'); select currval('accounts_id_seq') as id;");
		if ($dbhSys->GetNumberRows($result))
		{
			$aid = $dbhSys->GetValue($result, 0, "id");

			$dbh_acc = new CDatabase($settings_db_server, $ACCOUNT_DB, $settings_db_user, $settings_db_password, $settings_db_type);

			if (!$dbh_acc->connect())
			{
				// Email login information
				$message = "ERROR CREATING ACCOUNT:\n\n";
				$message .= $dbh_acc->getLastError()." \n\n";
				foreach ($data as $vname=>$vval)
					$message .= "$vname: $vval\n";
				$headers = array();
				$headers['From']  = $settings_no_reply;
				$headers['To']  = "sky.stebnicki@aereus.com";
				$headers['Subject']  = "Error creating database";
				// Create new email object
				$email = new Email();
				$status = $email->send($headers['To'], $headers, $message);
				unset($email);
			}
			else
			{

				$ures = $dbh_acc->Query("select id from users where name='default'");
				if ($dbh_acc->GetNumberRows($ures))
				{
					$uid = $dbh_acc->GetValue($ures, 0, "id");
					if ($uid)
					{
						$dbh_acc->Query("update accounts set id='$aid', name='$ACCOUNT_NAME', 
											title='".$dbh_acc->Escape($data['company'])."', 
											ts_started='now';");
						$dbh_acc->Query("update users set name='".$dbh_acc->Escape($data['username'])."', 
											password=md5('".$dbh_acc->Escape($data['password'])."'), 
											full_name='".$dbh_acc->Escape($data['first_name']." ".$data['last_name'])."', 
											account_id='$aid' where id='".$uid."';");
						$dbh_acc->Query("delete from email_domains;");
						$dbh_acc->Query("delete from email_users;");
					}
				}
				else
				{
					$dbh_acc->Query("insert into accounts(id, name, title, ts_started) 
									 values('$aid', '$ACCOUNT_NAME', '".$dbh_acc->Escape($data['company'])."', 'now');");
					$dbh_acc->Query("insert into user_groups(id, name, account_id, f_default) 
									 values('-1', 'Administrators', '$aid', 'f');");
					$dbh_acc->Query("insert into users(id, name, password, full_name, account_id) 
									 values('-1', 'administrator', 'Password1', 'Admin Account', '$aid');");
					$dbh_acc->Query("insert into user_group_mem(user_id, group_id) values('-1', '-1');");
				
					$dbh_acc->Query("insert into users(name, password, full_name, account_id) 
									 values('".$dbh_acc->Escape($data['username'])."', md5('".$dbh_acc->Escape($data['password'])."'), 
											'".$dbh_acc->Escape($data['first_name']." ".$data['last_name'])."', '$aid');");
					$dbh_acc->Query("insert into user_group_mem(user_id, group_id) select id as user_id, 
									'-1' as group_id from users where name='".$dbh_acc->Escape($data['username'])."' and account_id='$aid';");
				}

				$INC_PATH = "system/";
				include("system/schema_updates.php");
				include("system/update_datasets.php");

				// Start customer_id_seq at 100000
				$dbh_acc->Query("SELECT setval('public.customers_id_seq', 100000, true);");

				// Set flag to start new wizard
				settingsAccountSet($dbh_acc, $aid, "general/acc_wizard_run", "f");

				// Enter account, contact, and opportunity into customers in ANT Account
				// --------------------------------------------------------------
				$CRAIG_UID = 417;

				// Contact first
				$cust = new AntApi_Customer($ant_cust_svr, "administrator", "Password1");
				$cust->setValue("first_name", $data['first_name']);
				$cust->setValue("last_name", $data['last_name']);
				$cust->setValue("phone_work",$data['phone']);
				$cust->setValue("website", $data['website']);
				$cust->setValue("email", $data['email']);
				$cust->setValue("company", $data['company']);
				$cust->setValue("job_title", $data['job_title']);
				$cust->setValue("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']."\nCoupon:".$data['promotion_code']."\n");
				$cust->setValue("status_id", 12); // Active
				$cust->setValue("stage_id", 17); // Prospect
				$cust->setValue("owner_id", $CRAIG_UID); // Assign to craig strobeck
				$cust->setValue("type_id", CUST_TYPE_CONTACT);
				$cust->setMValue('groups', "210"); // ANT Users Group
				$custid_contact = $cust->save();

				/*
				$cust = new CAntCustomer($ant_cust_svr, "administrator", "Password1");
				$cust->setAttribute("first_name", $data['first_name']);
				$cust->setAttribute("last_name", $data['last_name']);
				$cust->setAttribute("phone_work",$data['phone']);
				$cust->setAttribute("website", $data['website']);
				$cust->setAttribute("email", $data['email']);
				$cust->setAttribute("company", $data['company']);
				$cust->setAttribute("job_title", $data['job_title']);
				$cust->setAttribute("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']."\nCoupon:".$data['promotion_code']."\n");
				$cust->setAttribute("status_id", 12); // Active
				$cust->setAttribute("stage_id", 17); // Prospect
				$cust->setAttribute("owner_id", $CRAIG_UID); // Assign to craig strobeck
				$cust->setAttribute("type_id", CUST_TYPE_CONTACT);
				$cust->setMvalAttribute('groups', "210"); // ANT Users Group
				//$cust = new CCustomer($dbh, null, $CRAIG_UID);
				$custid_contact = $cust->save();
				*/
				$dbh_acc->Query("update users set customer_number='$custid_contact' where name='".$dbh_acc->Escape($data['username'])."';");

				// account
				if (!$data['temp_company'])
				{
					switch (strtolower($data['promotion_code']))
					{
					case 'stimulous2010':
						$timeexp = "1 year";
						break;
					default:
						$timeexp = "30 days";
						break;
					}

					$cust = new AntApi_Customer($ant_cust_svr, "administrator", "Password1");
					$cust->setValue("name", $data['company']);
					$cust->setValue("type_id", CUST_TYPE_ACCOUNT);
					$cust->setValue("ant_account", $ACCOUNT_NAME);
					$cust->setValue("ant_edition", $data['edition']);
					$cust->setValue("ant_num_users", $data['num_users']);
					$cust->setValue("ant_trial_exp", date("m/d/Y", strtotime("+ $timeexp", time())));
					$cust->setValue("phone_work", $data['phone']);
					$cust->setValue("website", $data['website']);
					$cust->setValue("email", $data['email']);
					$cust->setValue("email2", $data['username']."@".$data['account_name'].".".$settings_localhost_root);
					$cust->setValue("company", $data['company']);
					$cust->setValue("job_title", $data['job_title']);
					$cust->setValue("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']."\nCoupon:".$data['promotion_code']."\n");
					$cust->setValue("status_id", 12); // Active
					$cust->setValue("stage_id", 17); // Prospect
					$cust->setValue("owner_id", $CRAIG_UID); // Assign to craig strobeck
					$cust->setMValue("groups", ($data['reseller'])?214:149); // Put into ANT Accounts, if reseller then "ANT Resellers" group
					$cust->addRelationship($custid_contact);
					$custid_acct = $cust->save();

					if ($custid_acct)
					{
						$websource = 7;
						$price = ($EDITION=='enterprise') ? 39 : 20;
						$amount = $price*$data['num_users'];

						$opp = new AntApi_Object($ant_cust_svr, "administrator", "Password1", "opportunity");
						$opp->setValue("created_by", "website");
						$opp->setValue("owner_id", $CRAIG_UID);
						$opp->setValue("name", "ANT Signup - ".$data['company']);
						$opp->setValue("amount", $amount);
						$opp->setValue("probability_per", 25);
						$opp->setValue("customer_id", $custid_acct);
						$opp->setValue("lead_source_id", $websource);
						$opp->setValue("type_id", 7); // ANT
						$opp->setValue("stage_id", 3); // Trial

						$opp->save();
					}
				}

				// Update customer_number in account
				if ($custid_acct || $data['account_id'])
				{
					if ($custid_acct)
						$dbhSys->Query("update accounts set customer_number='$custid_acct' where id='$aid'");

					$cnum = (is_numeric($data['account_id'])) ? $data['account_id'] : $custid_acct;
					if ($cnum)
						$dbhSys->Query("update accounts set billing_customer_number='$cnum' where id='$aid'");
				}
				else
				{
					// Email error
					$message = "ERROR CREATING CUSTOMER:\n\n";
					$message .= "Contact: $custid_contact\n";
					$message .= "Account: $custid_acct\n";
					if ($cust)
						$message .= $cust->m_resp." \n\n";
					foreach ($data as $vname=>$vval)
						$message .= "$vname: $vval\n";
					$headers = array();
					$headers['From']  = $settings_no_reply;
					$headers['To']  = "sky.stebnicki@aereus.com";
					$headers['Subject']  = "Error creating customer-opportunity";
					// Create new email object
					$email = new Email();
					$status = $email->send($headers['To'], $headers, $message);
					unset($email);
				}

				// Enter account, contact, and opportunity into customers in reseller ANT account
				// --------------------------------------------------------------
				if ($data['reseller'] && $data['reseller_ant'])
				{
					// Contact first
					$cust = new AntApi_Customer($ant_cust_svr, "administrator", "Password1");
					$cust->setValue("first_name", $data['first_name']);
					$cust->setValue("last_name", $data['last_name']);
					$cust->setValue("phone_work", $data['phone']);
					$cust->setValue("website", $data['website']);
					$cust->setValue("email", $data['email']);
					$cust->setValue("company", $data['company']);
					$cust->setValue("job_title", $data['job_title']);
					$cust->setValue("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']);
					$cust->setValue("type_id", CUST_TYPE_CONTACT);

					/*
					$cust = new CAntCustomer($data['reseller_ant'], "administrator", "Password1");
					$cust->setAttribute("first_name", $data['first_name']);
					$cust->setAttribute("last_name", $data['last_name']);
					$cust->setAttribute("phone_work", $data['phone']);
					$cust->setAttribute("website", $data['website']);
					$cust->setAttribute("email", $data['email']);
					$cust->setAttribute("company", $data['company']);
					$cust->setAttribute("job_title", $data['job_title']);
					$cust->setAttribute("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']);
					$cust->setAttribute("type_id", CUST_TYPE_CONTACT);
					*/
					$custid_contact = $cust->save();

					// account
					if (!$data['company'])
					{
						$cust = new AntApi_Customer($ant_cust_svr, "administrator", "Password1");
						$cust->setValue("name", $data['company']);
						$cust->setValue("type_id", CUST_TYPE_ACCOUNT);
						$cust->setValue("phone_work", $data['phone']);
						$cust->setValue("website", $data['website']);
						$cust->setValue("email", $data['email']);
						$cust->setValue("email2", $data['username']."@".$data['account_name'].".".$settings_localhost_root);
						$cust->setValue("company", $data['company']);
						$cust->setValue("job_title", $data['job_title']);
						$cust->setValue("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']);
						$cust->addRelationship($custid_contact);
						/*
						$cust = new CAntCustomer($data['reseller_ant'], "administrator", "Password1");
						$cust->setAttribute("name", $data['company']);
						$cust->setAttribute("type_id", CUST_TYPE_ACCOUNT);
						$cust->setAttribute("phone_work", $data['phone']);
						$cust->setAttribute("website", $data['website']);
						$cust->setAttribute("email", $data['email']);
						$cust->setAttribute("email2", $data['username']."@".$data['account_name'].".".$settings_localhost_root);
						$cust->setAttribute("company", $data['company']);
						$cust->setAttribute("job_title", $data['job_title']);
						$cust->setAttribute("notes", "Generated by ANT signup page\nPotential users:\n".$data['num_users']);
						//$cust->setAttribute("status_id", 12); // Active
						//$cust->setAttribute("stage_id", 17); // Prospect
						//$cust->setAttribute("owner_id", $CRAIG_UID); // Assign to craig strobeck
						//$cust->setMvalAttribute("groups", ($data['reseller'])?214:149); // Put into ANT Accounts group, if reseller place under "ANT Resellers" group
						$cust->addRelationship($custid_contact);
						*/
						$custid_acct = $cust->save();

						if ($custid_acct)
						{
							$websource = 7;
							$price = ($EDITION=='enterprise') ? 39 : 20;
							$amount = $price*$data['num_users'];

							$opp = new AntApi_Object($ant_cust_svr, "administrator", "Password1", "opportunity");
							$opp->setValue("created_by", "website");
							$opp->setValue("name", "ANT Signup - ".$data['company']);
							$opp->setValue("probability_per", 50);
							$opp->setValue("customer_id", $custid_acct);

							/*
							$opp = new CAntOpportunity($data['reseller_ant'], "administrator", "Password1");
							$opp->setAttribute("created_by", "website");
							//$opp->setAttribute("owner_id", $CRAIG_UID);
							$opp->setAttribute("name", "ANT Signup - ".$data['company']);
							//$opp->setAttribute("amount", $amount);
							$opp->setAttribute("probability_per", 50);
							$opp->setAttribute("customer_id", $custid_acct);
							//$opp->setAttribute("lead_source_id", $websource);
							//$opp->setAttribute("type_id", 7); // ANT
							//$opp->setAttribute("stage_id", 3); // Trial
							*/
							$opp->save();
						}
						else
						{
							// Email error
							$message = "ERROR CREATING CUSTOMER:\n\n";
							$message .= $cust->m_resp." \n\n";
							foreach ($data as $vname=>$vval)
								$message .= "$vname: $vval\n";
							$headers = array();
							$headers['From']  = $settings_no_reply;
							$headers['To']  = "sky.stebnicki@aereus.com";
							$headers['Subject']  = "Error creating customer-opportunity";
							// Create new email object
							$email = new Email();
							$status = $email->send($headers['To'], $headers, $message);
							unset($email);
						}
					}
				}

				// Email login information
				$message = "Congratulations!\n\n";
				$message .= "Your account has been created and is ready to start using!\n\n";
				$message .= "To login navigate to: ";
				$message .= "http://".$data['account_name'].".$settings_localhost_root\n\n";
				$message .= "Your user name is: ".$data['username']."\n\n";
				$message .= "Feel free to email support@aereus.com or call (800) 974-5061 if you need assistance.";
				$headers = array();
				$headers['From']  = $settings_no_reply;
				$headers['To']  = $data['email'];
				$headers['Subject']  = "Aereus Network Tools Account";
				// Create new email object
				$email = new Email();
				$status = $email->send($headers['To'], $headers, $message);
				unset($email);
				/*
				echo "<h1>Congratulations!</h1>";
				echo "<h3>Your account has been created</h3>";
				echo "<br />";
				echo "<p>To login navigate to: 
						<a href='http://".$_POST['account_name'].".$settings_localhost_root'>http://".$_POST['account_name'].".$settings_localhost_root</a></p>";
				echo "<p>This is your unique account site. Please bookmark or write the address down for future reference</p>";
				echo "<br />";
				echo "<p>Your user name is: <span style='font-weight:bold;'>".$_POST['username']."</span></p>";
				 */

				$dbh_acc->close();
			}
		}
	}
?>
